#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/CloudCIX/gocloudcix,github.com/stainless-sdks/gocloudcix-go"

go build -o terraform-provider-cloudcix
