#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/CloudCIX/gocloudcix,github.com/stainless-sdks/gocloudcix-go"

REPLACEMENT="${1:-"../gocloudcix-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/CloudCIX/gocloudcix="$REPLACEMENT"
go mod tidy -e
