#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/CloudCIX/gocloudcix,github.com/stainless-sdks/gocloudcix-go"

echo "==> Running tests"
go test ./... "$@"
